server:
  port: 4040
  error:
    include-stacktrace: always
    include-message: always
    include-exception: true
    include-binding-errors: always

spring:
  application:
    name: toxic-soap
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:3306/toxicdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USER:toxic}
    password: ${DB_PASSWORD:toxic123}
  sql:
    init:
      mode: always
  thymeleaf:
    cache: false

cxf:
  path: /ws
  servlet:
    init:
      service-list-path: /services

# Logging - verbose for testing
logging:
  level:
    root: INFO
    com.toxicsoap: DEBUG
    org.apache.cxf: DEBUG

# Application specific config
toxic-soap:
  auth:
    users:
      - username: user
        password: user123
        role: USER
      - username: admin
        password: admin123
        role: ADMIN
      - username: guest
        password: guest
        role: GUEST
